CREATE DATABASE npudb;

USE npudb;

CREATE TABLE IF NOT EXISTS npudb.user (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(45) NOT NULL,
  password VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  nickname VARCHAR(45) NOT NULL,
  created_by VARCHAR(100) NOT NULL,
  created_date TIMESTAMP NOT NULL DEFAULT 0,
  updated_by VARCHAR(100) NOT NULL,
  updated_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE INDEX username_UNIQUE (username ASC)
)ENGINE = InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS npudb.recipe (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  description VARCHAR(255) NOT NULL,
  difficulty TINYINT(1) UNSIGNED NULL,
  serving_amount INT UNSIGNED NULL,
  cooking_time INT UNSIGNED NULL,
  ingredient VARCHAR(1000) NULL,
  direction VARCHAR(5000) NULL,
  nutrition_fact VARCHAR(1000) NULL,
  image_url VARCHAR(255) NULL,
  category VARCHAR(100) NULL,
  user_id INT UNSIGNED NOT NULL,
  created_by VARCHAR(100) NOT NULL,
  created_date TIMESTAMP NOT NULL DEFAULT 0,
  updated_by VARCHAR(100) NOT NULL,
  updated_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id)
    REFERENCES npudb.user (id)
)ENGINE = InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS npudb.rank (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  rank TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  recipe_id INT UNSIGNED NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  created_by VARCHAR(100) NOT NULL,
  created_date TIMESTAMP NOT NULL DEFAULT 0,
  updated_by VARCHAR(100) NOT NULL,
  updated_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
    FOREIGN KEY (user_id)
    REFERENCES npudb.user (id),
  CONSTRAINT recipe_id
    FOREIGN KEY (recipe_id)
    REFERENCES npudb.recipe (id)
)ENGINE = InnoDB DEFAULT CHARSET=utf8;

